# version: "3.9"
services:
  fastapi:
    image: fastapi
    restart: always
    ports:
      - 0.0.0.0:80:80
    environment:
      - CONNECTION=mysql+mysqlconnector://fls:fls@mysql:3306/test
    depends_on:
      mysql:
        # condition: service_completed_successfully 
        condition: service_healthy
        
networks:
  default:
    name: api
