services:
  mysql:
    image: 'docker.io/mysql:latest'
    restart: always
    container_name: fastapi-mysql
    volumes:
      - mysql:/var/lib/mysql  #挂载目录，持久化存储
    ports:
      - '0.0.0.0:3306:3306'
    environment:
      TZ: Asia/Shanghai
      MYSQL_ROOT_PASSWORD: 'root'
      MYSQL_USER: 'fls'  #创建普通用户
      MYSQL_PASSWORD: 'fls'
      MYSQL_DATABASE: 'test'
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 4

volumes:
  mysql:

networks:
  default:
    name: api
